logging:
    version: 1
    formatters:
        brief:
            format: '%(message)s'
        default:
            format: '%(asctime)s %(levelname)-8s [%(name)s] %(message)s'
            datefmt: '%Y-%m-%d %H:%M:%S'
    handlers:
        console:
            class: logging.StreamHandler
            level: DEBUG
        file:
            class: logging.FileHandler
            level: DEBUG
            formatter: default
            filename: .\logs\main.log
        error_file:
            class: logging.FileHandler
            level: DEBUG
            formatter: default
            filename: .\logs\error.log
    loggers:
        main:
            level: DEBUG
            handlers: [ file ]
        error:
            level: DEBUG
            handlers: [ error_file ]

urls:
    #Antakalis
    url: 'https://www.aruodas.lt/namai/vilniuje/antakalnyje/'

    #Aukštieji Paneriai
#    url: 'https://www.aruodas.lt/namai/vilniuje/aukstuosiuose-paneriuose/'

    #Bajorai
#    url: 'https://www.aruodas.lt/namai/vilniuje/bajoruose/'

    #Baltupiai
#    url: 'https://www.aruodas.lt/namai/vilniuje/baltupiuose/'

    #Dvarcionys
#    url: 'https://www.aruodas.lt/namai/vilniuje/dvarcionyse/'

    #Fabijoniškės
#    url: 'https://www.aruodas.lt/namai/vilniuje/fabijoniskese/'

    #Jeruzalė
#    url: 'https://www.aruodas.lt/namai/vilniuje/jeruzaleje/'

    #Justiniškės
#    url: 'https://www.aruodas.lt/namai/vilniuje/justiniskese/'

    #Karoliniškės
#    url: 'https://www.aruodas.lt/namai/vilniuje/karoliniskese/'

    #Lazdynai
#    url: 'https://www.aruodas.lt/namai/vilniuje/lazdynuose/'

    #Lazdynėliai
#    url: 'https://www.aruodas.lt/namai/vilniuje/lazdyneliuose/'

    #Liepkalnis
#    url: 'https://www.aruodas.lt/namai/vilniuje/liepkalnyje/'

    #Markuciai
#    url: 'https://www.aruodas.lt/namai/vilniuje/markuciuose/'

    #Naujamiestis
#    url: 'https://www.aruodas.lt/namai/vilniuje/naujamiestyje/'

    #Naujininkai
#    url: 'https://www.aruodas.lt/namai/vilniuje/naujininkuose/'

    #Pašilaiciai
#    url: 'https://www.aruodas.lt/namai/vilniuje/pasilaiciuose/'

    #Pavilnys
#    url: 'https://www.aruodas.lt/namai/vilniuje/pavilnyje/'

    #Pilaitė
#    url: 'https://www.aruodas.lt/namai/vilniuje/pilaiteje/'

    #Rasos
#    url: 'https://www.aruodas.lt/namai/vilniuje/rasose/'

    #Santariškės
#    url: 'https://www.aruodas.lt/namai/vilniuje/santariskese/'

    #Saulėtekis
#    url: 'https://www.aruodas.lt/namai/vilniuje/sauletekyje/'

    #Senamiestis
#    url: 'https://www.aruodas.lt/namai/vilniuje/senamiestyje/'

    #Šnipiškės
#    url: 'https://www.aruodas.lt/namai/vilniuje/snipiskese/'

    #Turniškės
#    url: 'https://www.aruodas.lt/namai/vilniuje/turniskese/'

    #Užupis
#    url: 'https://www.aruodas.lt/namai/vilniuje/uzupyje/'

    #Valakampiai
#    url: 'https://www.aruodas.lt/namai/vilniuje/valakampiuose/'

    #Verkiai
#    url: 'https://www.aruodas.lt/namai/vilniuje/verkiuose/'

    #Vilkpėdė
#    url: 'https://www.aruodas.lt/namai/vilniuje/vilkpedeje/'

    #Žemieji Paneriai
#    url: 'https://www.aruodas.lt/namai/vilniuje/zemuosiuose-paneriuose/'

    #Žirmūnai
#    url: 'https://www.aruodas.lt/namai/vilniuje/zirmunuose/'

    #Žvėrynas
#    url: 'https://www.aruodas.lt/namai/vilniuje/zveryne/'